name: "db-log-reader"
description: "db log reader"
inputs:
  DB-name:
    description: "DB name"
    required: false
    default: IoTDB12

runs:
  using: "composite" # Mandatory parameter
  steps:
      - if: ${{ inputs.DB-name=='IoTDB12' && runner.os == 'Windows' }}
        name: Run DB
        shell: bash
        run: |
            if [ "$RUNNER_OS" == "Windows" ]; then
              "${GITHUB_WORKSPACE}/.github/scripts/dataSourcesLog/iotdb12_windows.sh"
            fi